name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  major:
    description: 'Major version'
    required: true
    default: 1
  minor:
    description: 'Minor version'
    required: true
    default: 0
  patch:
    description: 'Patch version'
    required: false
  revision:
    description: 'Revision version'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'